#This is a PowerShell script to automate bat files in specific orders
#The general time is 30 seconds, depending on internet speed may need to increase. May add adjustable variable later. 

start-process 1vs100.bat
Start-Sleep 30
start-process BeatBobby.bat
Start-Sleep 30
start-process Bigfoot.bat
Start-Sleep 30
start-process Blockbusters.bat
Start-Sleep 30
start-process CardSharks.bat
Start-Sleep 30
start-process Chopped.bat
Start-Sleep 30
start-process Exit.bat
Start-Sleep 30
start-process FamilyFeud1.bat
Start-Sleep 30
start-process FearFactor.bat
Start-Sleep 30
start-process Forged.bat
Start-Sleep 30
start-process Glads.bat
Start-Sleep 30
start-process HellsK.bat
Start-Sleep 30
start-process Holey.bat
Start-Sleep 30
start-process Hollywood.bat
Start-Sleep 30
start-process LMAD.bat
Start-Sleep 30
start-process ManVsFood.bat
Start-Sleep 30
start-process MasterChef.bat
Start-Sleep 30
start-process MatchGame.bat
Start-Sleep 30
start-process Millionaire.bat
Start-Sleep 30
start-process MomentOfT.bat
Start-Sleep 30
start-process OCC.bat
Start-Sleep 30
start-process Paternity.bat
Start-Sleep 30
start-process PawnStars.bat
Start-Sleep 30
start-process Pointless.bat
Start-Sleep 30
start-process Pooch.bat
Start-Sleep 30
start-process PriceIsRight.bat
Start-Sleep 30
start-process RBT.bat
Start-Sleep 30
start-process StorageWars.bat
Start-Sleep 30
start-process Wall.bat
Start-Sleep 30
start-process WheelOfFortune.bat
Start-Sleep 30
start-process Min2Win.bat
Start-Sleep 30
start-process Maury.bat
Start-Sleep 30
start-process Drag.bat
Start-Sleep 30
start-process DealOrNo.bat
Start-Sleep 30
start-process Queen.bat
Start-Sleep 30
start-process Kard.bat
Start-Sleep 30
start-process Distraction.bat
Start-Sleep 30
start-process Chopjr.bat
Start-Sleep 30
start-process Oscars.bat
Start-Sleep 30
start-process Football.bat
Start-Sleep 30
start-process Roast.bat
Start-Sleep 30
start-process Chase.bat
Start-Sleep 30
start-process Gong.bat
Start-Sleep 30
start-process ANW.bat

Start-Sleep 30
start-process DownloadViews.bat


#C:\Users\Gordon\Desktop\Wonderful Moments\0 - EveryProject\Backend\Bat
